add_info = {'items': [{'First': 'Frederik',
	'Last': 'Aasaaren',
	'School': 'CC',
	'Year': '2015',
	'Side': 'Port'},

	{'First': 'Justin',
	'Last': 'Bae',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Starboard'},

	{'First': 'Andrew',
	'Last': 'Bartholomew',
	'School': 'GS',
	'Year': '2016',
	'Side': 'Port'},

	{'First': 'Matt',
	'Last': 'Bellesheim',
	'School': 'CC',
	'Year': '2015',
	'Side': 'Port/Starboard'},

	{'First': 'Benjamin',
	'Last': 'Blair',
	'School': 'CC',
	'Year': '2015',
	'Side': 'Port/Starboard'},

	{'First': 'Jakub',
	'Last': 'Buczek',
	'School': 'CC',
	'Year': '2016',
	'Side': 'Starboard'},

	{'First': 'Colin',
	'Last': 'Conroy',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Starboard'},

	{'First': 'Trevor',
	'Last': 'Docter',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Port'},

	{'First': 'Max',
	'Last': 'Fenner',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Starboard'},

	{'First': 'Darius',
	'Last': 'Grayer',
	'School': 'SEAS',
	'Year': '2015',
	'Side': 'Port/Starboard'},

	{'First': 'Oliver',
	'Last': 'Grueterich',
	'School': 'SEAS',
	'Year': '2017',
	'Side': 'Port'},

	{'First': 'Jeffrey',
	'Last': 'Hou',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Port'},

	{'First': 'Oliver',
	'Last': 'Ingram',
	'School': 'CC',
	'Year': '2016',
	'Side': 'Port'},

	{'First': 'Oliver',
	'Last': 'Jennings',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Port/Starboard'},

	{'First': 'Ryan',
	'Last': 'Koo',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Starboard'},

	{'First': 'Petros',
	'Last': 'Krommidas',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Starboard'},

	{'First': 'Benjamin',
	'Last': 'Landis',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Port'},

	{'First': 'Ryan',
	'Last': 'Madani',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Port'},

	{'First': 'John',
	'Last': 'Maloney',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Starboard'},

	{'First': 'Brian',
	'Last': 'McGrattan',
	'School': 'SEAS',
	'Year': '2015',
	'Side': 'Port/Starboard'},

	{'First': 'Jeff',
	'Last': 'Monahan',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Port/Starboard'},

	{'First': 'David',
	'Last': 'Mottola',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Starboard'},

	{'First': 'Conor',
	'Last': 'Murphy',
	'School': 'CC',
	'Year': '2016',
	'Side': 'Starboard'},

	{'First': 'Bryan',
	'Last': 'Ptucha',
	'School': 'SEAS',
	'Year': '2015',
	'Side': 'Port/Starboard'},

	{'First': 'Daniel',
	'Last': 'Puttmann',
	'School': 'SEAS',
	'Year': '2016',
	'Side': 'Starboard'},

	{'First': 'Noah',
	'Last': 'Rivkin',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Port'},

	{'First': 'Jonathon',
	'Last': 'Rosow',
	'School': 'CC',
	'Year': '2016',
	'Side': 'Starboard'},

	{'First': 'Colin',
	'Last': 'Ross',
	'School': 'CC',
	'Year': '2016',
	'Side': 'Port'},

	{'First': 'Solomon',
	'Last': 'Seckler',
	'School': 'CC',
	'Year': '2017',
	'Side': 'Port'},

	{'First': 'Travis',
	'Last': 'Simon',
	'School': 'CC',
	'Year': '2015',
	'Side': 'Starboard'},

	{'First': 'Colm',
	'Last': 'Smith',
	'School': 'CC',
	'Year': '2016',
	'Side': 'Starboard'},

	{'First': 'William',
	'Last': 'Solberg',
	'School': 'GS',
	'Year': '2016',
	'Side': 'Port'},

	{'First': 'Jason',
	'Last': 'Swann',
	'School': 'GS',
	'Year': '2016',
	'Side': 'Port/Starboard'},

	{'First': 'Harrison',
	'Last': 'Vincent',
	'School': 'CC',
	'Year': '2018',
	'Side': 'Port'},

	{'First': 'Griffin',
	'Last': 'Whitlock',
	'School': 'CC',
	'Year': '2015',
	'Side': 'Port/Starboard'},

	{'First': 'Duo',
	'Last': 'Xu',
	'School': 'CC',
	'Year': '2015',
	'Side': 'Port/Starboard'}]}